name: Rohit Selenium SignUp Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout code
        uses: actions/checkout@v4

     
      - name: Java 11 setup
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      
      - name: Chrome install
        uses: browser-actions/setup-chrome@v1

     
      - name: Maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      
      - name: Compile karo
        run: mvn compile

     
      - name: Selenium test chalao
        run: mvn exec:java -Dexec.mainClass="RohitShatty_SignUp"
